### ISSUE TITLE
TODO-List

### ISSUE THREAD

**Issue by grayfallstown** [grayfallstown/win-my-life#1]
### Reward System
- [ ] points for doing stuff
- [ ] optional sounds for earning points, reaching milestones
- [ ] rewards for hitting milestones in points during the day, like a nice animation with sound
- [ ] many interaction animations like flicking buttons (can be disabled)
- [ ] overlay animations over whatever is shown on all connected devices?

### Keep going
- [ ] System-message to display what you should be doing right now with ability to skip or mark as done
- [ ] ability to quick check multiple routines quickly, possibly in system message
- [ ] randomly suggest tasks via system messages that are in the future

### Data Structure
- [ ] multiple, separate planners: basics, household, medical, work, official personal stuff, user defined one with selectable or user defined icons
	- [ ] separate planners have work-time (7-9 + 17-21), like work related stuff will only be shown during business hours
- [ ] projects, that are similar to planners
- [ ] organize tasks in groups
- [ ] organize tasks relative to each other, with deadlines and when to start
- [ ] reoccuring tasks as routines
- [ ] track points and done tasks (the concrete task objects) over time
- [ ] command on data pattern

### Technical stuff
- [ ] fully offline, optional sync across devices
- [ ] primarily as mobile and desktop apps

### Screens
- [ ] note taking, points for taking notes
- [ ] screen for "routine tasks you could improve in" (often skipped or left undone stuff)

### Media
- [ ] Create an initial logo design
- [ ] imagary for each section. multiple ai generated images, constantly changing, shuffled
- [ ] combining and mixing sounds and animations to create more variaty

### Sync
- [ ] Sync server that you can host and make public, have to login to and that uses client encryption

### Unsorted / Other
- [ ] no login / ad free
- [ ] add quick-add premade tasks with search or ai suggestion
